#!/usr/local/bin/perl -n

# bdfimplode from the "GNU unifont" project
# http://czyborra.com/unifont/bdfimplode

if (/^ENCODING\s+(\d+)/) { printf ("%04X:", $1); }
elsif (/^BITMAP/) { $BITMAP=1; }
elsif (/^ENDCHAR/) { $BITMAP=0; print "\n"; }
elsif ($BITMAP) { y/a-f/A-F/; s/\n$//; print; }
