#!/usr/local/bin/perl

# hexmerge from the "GNU unifont" project
# http://czyborra.com/unifont/hexmerge
#
# usage: hexmerge [input.hex ...] > output.hex
# later files take precedence if multiple files provide the same character

while (<>)
{
	$G{uc($1)}=$2 if /^(....):(.+)\n/;
}

for (sort keys %G)
{
	print "$_:$G{$_}\n";
}
